version: '3'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword123
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  nestjs-app:
    build:
      context: .
    container_name: nestjs-app
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://admin:adminpassword123@mongo:27017/nest_db?authSource=admin
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:dev

volumes:
  mongo-data:
